### ISSUE TITLE
Userstyles selectively discards "global" comments

### ISSUE THREAD

**Issue by hideheader** [stylish-userstyles/userstyles#86]
"Userstyles selectively discards "global" comments, those which aren't contained in a @document rule. If the text between @document rules includes something besides comments and whitespace, that content is retained as a global code section. If not, it's discarded. Licensing information, hints to other coders, and ASCII dinosaurs are all lost to Chrome users. That's bad."
https://forum.userstyles.org/discussion/48232/bug-ish-namespace-creates-a-global-style-c-in-chrome

**Comment by JasonBarnabe** [comment]
The idea is to avoid global sections and having Stylish think these are global styles. This can probably be done better, but that's the reason why it does what it does.

**Comment by hideheader** [comment]
OK, but Stylish/Firefox has been adding `@namespace` to new styles for a long time now, so that horse is already out of the barn. Fixing this on the Stylish/Chrome side is easy, a matter of checking for paired braces in the global sections. On the Userstyles side I don't know - I recall that validator required at one point that comments be removed, and that replacing them was a chore.

**Comment by JasonBarnabe** [comment]
There's not a clear line of delineation between what userstyles will do for Chrome and what Stylish itself will do with its import feature. It'd probably be good to figure this out.
