### ISSUE TITLE
[Feature request] Add a link for 'My Reviews'

### ISSUE THREAD

**Issue by hideheader** [stylish-userstyles/userstyles#87]
Currently 'My Discussions' returns only discussions that aren't reviews. 
https://forum.userstyles.org/discussion/48222/bug-only-the-first-4-pages-of-my-discussions-return-discussions

Unintentional perhaps, but that's actually pretty useful. The old behaviour is still available from the user profile, but a link to it from the category pages would be better. Best would be to filter 'My Discussions' (and maybe 'Participated Discussions') with the same category filter used to produce the currently viewed category, so that 'My Discussions' on 'Style Reviews' would return only 'My Reviews', all except reviews on 'All Categories', and so on.

**Comment by leotm** [comment]
+1
![my-discussions-none](https://cloud.githubusercontent.com/assets/1881059/15986864/23857a7c-300c-11e6-9018-0278603a8eb2.PNG)

**Comment by leotm** [comment]
Note: this behavior also happens in _My Bookmarks_.
