### ISSUE TITLE
[Vanilla] I can see which posts other users have (not) read

### ISSUE THREAD

**Issue by hideheader** [stylish-userstyles/userstyles#89]
When logged in and viewing another user's profile, bold entries are items which I haven't read. When not logged in, bold entries are what they haven't read.
https://forum.userstyles.org/discussion/48222/bug-only-the-first-4-pages-of-my-discussions-return-discussions#Comment_101388

**Comment by hideheader** [comment]
OK, this seems to be a Vanilla thing which may or may not want to fix. I'll leave this issue in place as a tracker for now, but it's not actionable in this repository.
https://forum.userstyles.org/discussion/46669/styling-visited-threads-on-forum-userstyles-org-2

**Comment by JasonBarnabe** [comment]
I've sent them an e-mail. I will close this when they've fixed it or they say I can post it on their repo.
