### ISSUE TITLE
[Feature request] Subcategorize browser themes

### ISSUE THREAD

**Issue by hideheader** [stylish-userstyles/userstyles#96]
'Find styles for this site...' should deliver themes specifically for `about:reader`, `about:home`, `about:blank`, etc. but cannot unless browser themes are sorted by subcategory and search operates on these domains as it does on site domains.

Currently these are '@category app @subcategory browser' styles, so perhaps what I'm asking for is to sort app styles which have chrome `@document` targets into corresponding subcategories.

**Comment by JasonBarnabe** [comment]
The original reason they're all grouped together is because there weren't enough to differentiate. Maybe that's different now.

**Comment by hideheader** [comment]
My use-case here was that when I used "Find styles for this site..." to find `about:reader` styles I got a 100 pages of 'Browser themes and skins' which included no Reader styles in the first 10 pages. There are fewer than 20 Reader themes; around [365 `about:*` themes](https://userstyles.org/styles/browse?search_terms=about+NEAR%2F1+%28firefox|about|accounts|addons|app-manager|buildconfig|cache|config|crashes|credits|customizing|downloads|healthreport|home|license|logo|memory|mozilla|networking|newtab|permissions|plugins|preferences|privatebrowsing|rights|robots|serviceworkers|sessionrestore|stylish-edit|support|sync-log|sync-tabs|telemetry|webrtc|welcomeback%29+%40subcategory+browser) altogether.

Is it possible to force a search term in `fix_search_url` or elsewhere to patch up search without touching the subcategories? `reader @subcategory browser` returns about 20 Reader styles, `"about reader" @subcategory browser` returns about half of those, so maybe it's possible to refine the results for at least some `about:` URLs without rejiggering the subcategory assignments.
